### ISSUE TITLE
Can we get an updated Nuget Package for this?

### ISSUE THREAD

**Issue by Offline-R503B** [Dirkster99/AvalonEditHighlightingThemes#6]
Title,

I am also wondering how I would implement this in an existing project. Would love to use it! 

In our project we are currently using Catel MVVM + Fluent Orchestra. So far Avalon Edit functions as normal but the theme is awful.

All help will be greatly appreciated!

**Comment by Dirkster99** [comment]
Can you please specify what you need updated? Because I thought the package us up-to-date?

**Comment by Offline-R503B** [comment]
My main issue is that from the example I have a quite hard time understanding how to implement this into an existing project. 
I don't think a new nuget would solve that.

Sorry for the confusing title, I had some issues installing the nuget at first but that was on my end, as it turned out.

**Comment by Offline-R503B** [comment]
> Can you please specify what you need updated? Because I thought the package us up-to-date?

Closing, Adding new issue regarding demo.

**Comment by NotYoojun** [comment]
Hi there, any ideas on this? I'm considering making a fork of this project and then upload it into NuGet!
