### ISSUE TITLE
Need your help on Winform, thank you very much!

### ISSUE THREAD

**Issue by fuyuesong** [Dirkster99/AvalonEditHighlightingThemes#8]
Hello, thank you for sharing such a cool theme, I tried to use it in Winform's ICSharpCode.AvalonEdit without success. I'm not good at WPF. Could you please help me to make an example of Winform using this theme? thank you very much!

**Comment by Dirkster99** [comment]
Sorry, cannot help you with WinForms please work with the authors of ICSharpCode.AvalonEdit to get your problems resolved - soory again for the late notice and inability to help with this issue.
